// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: save_play.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_save_5fplay_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_save_5fplay_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_save_5fplay_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_save_5fplay_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_save_5fplay_2eproto;
namespace KwSave {
class SavePlayData;
struct SavePlayDataDefaultTypeInternal;
extern SavePlayDataDefaultTypeInternal _SavePlayData_default_instance_;
}  // namespace KwSave
PROTOBUF_NAMESPACE_OPEN
template<> ::KwSave::SavePlayData* Arena::CreateMaybeMessage<::KwSave::SavePlayData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace KwSave {

// ===================================================================

class SavePlayData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:KwSave.SavePlayData) */ {
 public:
  inline SavePlayData() : SavePlayData(nullptr) {}
  ~SavePlayData() override;
  explicit PROTOBUF_CONSTEXPR SavePlayData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SavePlayData(const SavePlayData& from);
  SavePlayData(SavePlayData&& from) noexcept
    : SavePlayData() {
    *this = ::std::move(from);
  }

  inline SavePlayData& operator=(const SavePlayData& from) {
    CopyFrom(from);
    return *this;
  }
  inline SavePlayData& operator=(SavePlayData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SavePlayData& default_instance() {
    return *internal_default_instance();
  }
  static inline const SavePlayData* internal_default_instance() {
    return reinterpret_cast<const SavePlayData*>(
               &_SavePlayData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SavePlayData& a, SavePlayData& b) {
    a.Swap(&b);
  }
  inline void Swap(SavePlayData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SavePlayData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SavePlayData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SavePlayData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SavePlayData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SavePlayData& from) {
    SavePlayData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SavePlayData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "KwSave.SavePlayData";
  }
  protected:
  explicit SavePlayData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kZFieldNumber = 2,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float z = 2;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:KwSave.SavePlayData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_save_5fplay_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SavePlayData

// float x = 1;
inline void SavePlayData::clear_x() {
  _impl_.x_ = 0;
}
inline float SavePlayData::_internal_x() const {
  return _impl_.x_;
}
inline float SavePlayData::x() const {
  // @@protoc_insertion_point(field_get:KwSave.SavePlayData.x)
  return _internal_x();
}
inline void SavePlayData::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void SavePlayData::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:KwSave.SavePlayData.x)
}

// float z = 2;
inline void SavePlayData::clear_z() {
  _impl_.z_ = 0;
}
inline float SavePlayData::_internal_z() const {
  return _impl_.z_;
}
inline float SavePlayData::z() const {
  // @@protoc_insertion_point(field_get:KwSave.SavePlayData.z)
  return _internal_z();
}
inline void SavePlayData::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void SavePlayData::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:KwSave.SavePlayData.z)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace KwSave

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_save_5fplay_2eproto
